/* ============================================================
   CosplayHub — Catálogo de dados (produtos e categorias)
   Imagens premium: Flickr/Wikimedia (CC, via Openverse)
   Fallback dinâmico: LoremFlickr + Picsum
   ============================================================ */

const CATEGORIAS = [
  { id: "anime",     nome: "Anime & Mangá",       icone: "bi-tv",                    tag: "cosplay,anime" },
  { id: "filmes",    nome: "Filmes & Séries",     icone: "bi-film",                  tag: "movie,costume" },
  { id: "games",     nome: "Games",               icone: "bi-controller",            tag: "gaming,costume" },
  { id: "heroes",    nome: "Super-Herois",        icone: "bi-lightning-charge-fill", tag: "superhero" },
  { id: "medieval",  nome: "Fantasia & Medieval", icone: "bi-shield-shaded",         tag: "medieval,knight" },
  { id: "acessorios", nome: "Acessórios & Props", icone: "bi-gem",                   tag: "mask,prop" },
];

const IMAGENS_CATEGORIAS = {
  anime: "https://live.staticflickr.com/5245/5337800379_4958bc0b14_b.jpg",
  filmes: "https://live.staticflickr.com/5507/14234974055_c78ac44de2_b.jpg",
  games: "https://live.staticflickr.com/7804/46900319441_ea8132fc39_b.jpg",
  heroes: "https://live.staticflickr.com/8243/8639237614_cc84d1ab96_b.jpg",
  medieval: "https://live.staticflickr.com/1368/1070850810_ae6d0f962e_b.jpg",
  acessorios: "https://live.staticflickr.com/7334/16405813122_7edbb3d50b_b.jpg",
};

const PRODUTOS = [
  {
    id: 1,
    nome: "Kimono Xadrez Tanjiro — Réplica Premium",
    categoria: "anime",
    preco: 289.90,
    precoAntigo: 349.90,
    avaliacao: 4.9,
    numAvaliacoes: 214,
    vendas: 512,
    novidade: false,
    destaque: true,
    tamanhos: ["P", "M", "G", "GG"],
    estoque: 14,
    tag: "kimono,japan",
    descricao:
      "Réplica fiel do kimono xadrez usado por Tanjiro Kamado. Tecido em sarja leve com estampa em alta definição, costuras reforçadas e caimento confortável para uso prolongado em convenções e eventos. Acompanha faixa obi decorativa.",
    especificacoes: [
      "Tecido: sarja de poliéster premium",
      "Estampa sublimada em alta definição",
      "Acompanha faixa obi",
      "Lavagem à máquina (ciclo delicado)",
    ],
    imagens: [
      "https://live.staticflickr.com/5578/14787278657_aa1c1b3c4a_b.jpg",
      "https://live.staticflickr.com/3847/14970724521_4ed83b2403_b.jpg",
      "https://live.staticflickr.com/3903/14973477392_a7eb085f15_b.jpg",
    ],
  },
  {
    id: 2,
    nome: "Manto Akatsuki — Nuvens Vermelhas Bordado",
    categoria: "anime",
    preco: 259.90,
    precoAntigo: 299.90,
    avaliacao: 4.8,
    numAvaliacoes: 187,
    vendas: 430,
    novidade: false,
    destaque: true,
    tamanhos: ["P", "M", "G", "GG"],
    estoque: 22,
    tag: "cloak,red",
    descricao:
      "O manto icônico da Akatsuki com nuvens vermelhas bordadas em alto relevo. Interior forrado, gola alta estruturada e tecido resistente ao vento — perfeito para composições de personagem ou uso casual geek.",
    especificacoes: [
      "Nuvens bordadas (não estampadas)",
      "Forro interno em cetim",
      "Gola alta estruturada",
      "Bolsos internos discretos",
    ],
    imagens: [
      "https://live.staticflickr.com/2846/10136081583_739f01be0c_b.jpg",
      "https://live.staticflickr.com/65535/54359124362_c73059e7ab_b.jpg",
      "https://live.staticflickr.com/3826/9783779234_219d702d24_b.jpg",
    ],
  },
  {
    id: 3,
    nome: "Uniforme de Feiticeiro Jujutsu — Edição Batalha",
    categoria: "anime",
    preco: 319.90,
    precoAntigo: null,
    avaliacao: 4.7,
    numAvaliacoes: 143,
    vendas: 265,
    novidade: true,
    destaque: true,
    tamanhos: ["P", "M", "G", "GG"],
    estoque: 9,
    tag: "cosplay,japan",
    descricao:
      "Uniforme escolar de feiticeiro com acabamento premium: gola alta assimétrica, botões metálicos gravados e tecido com leve elasticidade para liberdade de movimento durante performances e competições de cosplay.",
    especificacoes: [
      "Tecido com elastano (stretch)",
      "Botões metálicos gravados",
      "Costura dupla nos pontos de tensão",
      "Kit com 3 peças: casaco, calça e faixa",
    ],
    imagens: [
      "https://live.staticflickr.com/66/165063665_aafe3d177c_b.jpg",
      "https://live.staticflickr.com/3212/2774944633_ef12818bf3_b.jpg",
      "https://live.staticflickr.com/3378/3327449616_33eb4083ef_b.jpg",
    ],
  },
  {
    id: 4,
    nome: "Armadura de Samurai Completa — Aço Escovado",
    categoria: "medieval",
    preco: 1299.90,
    precoAntigo: 1499.90,
    avaliacao: 5.0,
    numAvaliacoes: 76,
    vendas: 98,
    novidade: false,
    destaque: true,
    tamanhos: ["Único"],
    estoque: 4,
    tag: "samurai,armor",
    descricao:
      "Armadura de samurai em EVA de alta densidade com pintura efeito aço escovado. Conjunto completo com dou (peitoral), kabuto (elmo), ombreiras, manicas e hakama. Montagem intuitiva com tiras de velcro ocultas.",
    especificacoes: [
      "EVA 10mm de alta densidade",
      "Pintura com efeito metálico",
      "Conjunto com 7 peças",
      "Ajuste por velcro e elásticos internos",
    ],
    imagens: [
      "https://live.staticflickr.com/2889/10320226203_ed65e06fac_b.jpg",
      "https://live.staticflickr.com/3002/2938707468_9bb6ea8fc1_b.jpg",
      "https://live.staticflickr.com/3229/2767202587_6aa9760f38_b.jpg",
    ],
  },
  {
    id: 5,
    nome: "Armadura de Cavaleiro Medieval — Guardião Real",
    categoria: "medieval",
    preco: 1199.90,
    precoAntigo: null,
    avaliacao: 4.8,
    numAvaliacoes: 64,
    vendas: 87,
    novidade: true,
    destaque: true,
    tamanhos: ["Único"],
    estoque: 6,
    tag: "knight,armor",
    descricao:
      "Armadura completa de cavaleiro com peitoral articulado, escarcela e elmo com viseira móvel. Ideais para LARP, feiras medievais e fotografia temática. Acabamento envelhecido artesanal peça a peça.",
    especificacoes: [
      "Viseira móvel funcional",
      "Peitoral articulado",
      "Acabamento envelhecido manual",
      "Suporte de exibição incluído",
    ],
    imagens: [
      "https://live.staticflickr.com/3726/9534915722_4148ebd3e0_b.jpg",
      "https://live.staticflickr.com/5485/9534916080_fb38831884_b.jpg",
      "https://live.staticflickr.com/3892/14987656768_f23f5f65b7_b.jpg",
    ],
  },
  {
    id: 6,
    nome: "Trajo Viking Ragnar — Pele e Malha de Combate",
    categoria: "medieval",
    preco: 899.90,
    precoAntigo: 999.90,
    avaliacao: 4.7,
    numAvaliacoes: 58,
    vendas: 74,
    novidade: false,
    destaque: true,
    tamanhos: ["M", "G", "GG"],
    estoque: 8,
    tag: "viking,warrior",
    descricao:
      "Trajo viking inspirado em séries épicas: túnica de malha metálica simulada, sobretudo de pele sintética, cinto de couro legítimo com fivela rúnica e perneiras. Um visual imponente e pronto para a batalha.",
    especificacoes: [
      "Couro legítimo no cinto",
      "Pele sintética premium",
      "Malha simulada leve (não é metal)",
      "4 peças + acessórios",
    ],
    imagens: [
      "https://live.staticflickr.com/242/518120820_5e021d4954_b.jpg",
      "https://live.staticflickr.com/4048/4636715942_4b33540d54_b.jpg",
      "https://live.staticflickr.com/790/40572500715_014f8f0c1f_b.jpg",
    ],
  },
  {
    id: 7,
    nome: "Capacete Stormtrooper — Réplica Colecionável",
    categoria: "filmes",
    preco: 649.90,
    precoAntigo: null,
    avaliacao: 4.6,
    numAvaliacoes: 112,
    vendas: 156,
    novidade: false,
    destaque: true,
    tamanhos: ["Único"],
    estoque: 11,
    tag: "helmet,starwars",
    descricao:
      "Réplica colecionável do capacete de Stormtrooper com lentes espelhadas e sistema interno de ajuste. Vem com base de exposição acrílica e certificado de edição limitada.",
    especificacoes: [
      "ABS injeção com pintura UV",
      "Lentes espelhadas removíveis",
      "Acolchoamento interno ajustável",
      "Base acrílica inclusa",
    ],
    imagens: [
      "https://live.staticflickr.com/5507/14234974055_c78ac44de2_b.jpg",
      "https://live.staticflickr.com/4872/46375962411_4537df5a19_b.jpg",
      "https://live.staticflickr.com/3789/19764079262_814b0022ef_b.jpg",
    ],
  },
  {
    id: 8,
    nome: "Manto de Jedi + Sabre de Luz Retrátil",
    categoria: "filmes",
    preco: 749.90,
    precoAntigo: 849.90,
    avaliacao: 4.8,
    numAvaliacoes: 95,
    vendas: 132,
    novidade: false,
    destaque: true,
    tamanhos: ["P", "M", "G", "GG"],
    estoque: 13,
    tag: "starwars,costume",
    descricao:
      "Kit completo de Jedi: manto externo com capuz profundo, túnica interna, faixa cinturão e sabre de luz retrátil com iluminação LED e efeitos sonoros de batalha. Que a Força esteja com você.",
    especificacoes: [
      "Sabre LED com som (pilhas inclusas)",
      "Lâmina retrátil de 90cm",
      "Manto em crepe pesado",
      "Kit com 5 peças",
    ],
    imagens: [
      "https://upload.wikimedia.org/wikipedia/commons/7/72/Star_Wars_Celebration_IV_-_Jedi_lightsaber_battle_fan_costumes_%284878898184%29.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/1/1b/Star_Wars_Celebration_IV_-_Jedi_lightsaber_duel_%284878881510%29.jpg",
      "https://live.staticflickr.com/6151/6188957269_ae29ebd5ee_b.jpg",
    ],
  },
  {
    id: 9,
    nome: "Capuz e Manto Sith — Edição Sombria",
    categoria: "filmes",
    preco: 599.90,
    precoAntigo: null,
    avaliacao: 4.5,
    numAvaliacoes: 71,
    vendas: 89,
    novidade: true,
    destaque: false,
    tamanhos: ["P", "M", "G", "GG"],
    estoque: 16,
    tag: "hood,black",
    descricao:
      "Conjunto de manto longo com capuz estruturado e túnica interna em tons profundos de preto e cinza. Silhueta dramática garantida — do lado sombrio direto para o palco do concurso de cosplay.",
    especificacoes: [
      "Capuz com armação interna removível",
      "Tecido fluído anti-amassado",
      "Comprimento total 145cm",
      "2 peças",
    ],
    imagens: [
      "https://live.staticflickr.com/65535/54359124362_c73059e7ab_b.jpg",
      "https://live.staticflickr.com/3378/3327449616_33eb4083ef_b.jpg",
      "https://live.staticflickr.com/4031/4635122384_1be7d7b323_b.jpg",
    ],
  },
  {
    id: 10,
    nome: "Jaqueta Cyberpunk Neon — Circuito Luminoso",
    categoria: "games",
    preco: 479.90,
    precoAntigo: 559.90,
    avaliacao: 4.9,
    numAvaliacoes: 168,
    vendas: 241,
    novidade: true,
    destaque: true,
    tamanhos: ["P", "M", "G", "GG"],
    estoque: 10,
    tag: "cyberpunk,neon",
    descricao:
      "Jaqueta futurista com trilhas de LED costuradas e controlador USB recarregável com 7 modos de luz. Tecido refletivo reage ao flash das câmeras — feita para arrancar suspiros na pista e nas fotos.",
    especificacoes: [
      "LEDs com 7 modos + controle USB",
      "Bateria recarregável (6h de autonomia)",
      "Tecido refletivo premium",
      "Lavável removendo o módulo eletrônico",
    ],
    imagens: [
      "https://live.staticflickr.com/3212/2774944633_ef12818bf3_b.jpg",
      "https://live.staticflickr.com/3826/9783779234_219d702d24_b.jpg",
      "https://live.staticflickr.com/2846/10136081583_739f01be0c_b.jpg",
    ],
  },
  {
    id: 11,
    nome: "Jaqueta Couro Vault Survivor — Pós-Apocalíptica",
    categoria: "games",
    preco: 399.90,
    precoAntigo: null,
    avaliacao: 4.6,
    numAvaliacoes: 87,
    vendas: 118,
    novidade: false,
    destaque: false,
    tamanhos: ["P", "M", "G", "GG"],
    estoque: 12,
    tag: "leather,jacket",
    descricao:
      "Jaqueta de couro sintético com patches bordados do Refúgio, zíperes metálicos YKK e forro térmico. Resistente, estilosa e pronta para sobreviver a qualquer wasteland — inclusive à fila da convenção.",
    especificacoes: [
      "Couro sintético PU premium",
      "Zíperes metálicos YKK",
      "Forro térmico removível",
      "Patches bordados exclusivos",
    ],
    imagens: [
      "https://live.staticflickr.com/2578/3789662155_da40f768d1_b.jpg",
      "https://live.staticflickr.com/5473/10062428925_81bac218f6_b.jpg",
      "https://live.staticflickr.com/54/174473714_6d5f2607d2_b.jpg",
    ],
  },
  {
    id: 12,
    nome: "Elmo do Cavaleiro do Abismo — RPG Sombrio",
    categoria: "games",
    preco: 549.90,
    precoAntigo: null,
    avaliacao: 4.7,
    numAvaliacoes: 49,
    vendas: 63,
    novidade: false,
    destaque: true,
    tamanhos: ["Único"],
    estoque: 7,
    tag: "helmet,armor",
    descricao:
      "Elmo inspirado nos cavaleiros sombrios dos RPGs de ação, com chifres esculpidos, viseira gradeada e interior acolchoado. Peça de destaque absoluto em qualquer composição dark fantasy.",
    especificacoes: [
      "Chifres em resina resistente",
      "Interior acolchoado removível",
      "Viseira gradeada ventilada",
      "Acabamento matte envelhecido",
    ],
    imagens: [
      "https://live.staticflickr.com/1409/854344979_3ade2ea1df_b.jpg",
      "https://live.staticflickr.com/1314/855199664_045daa271e_b.jpg",
    ],
  },
  {
    id: 13,
    nome: "Capa Wonder Warrior — Coroa e Braceletes",
    categoria: "heroes",
    preco: 449.90,
    precoAntigo: 519.90,
    avaliacao: 4.8,
    numAvaliacoes: 103,
    vendas: 147,
    novidade: false,
    destaque: true,
    tamanhos: ["P", "M", "G"],
    estoque: 15,
    tag: "superhero,red",
    descricao:
      "Conjunto de guerreira amazona com corpete estruturado, capa em cetim, tiara metálica e braceletes de combate. Modelagem anatômica que valoriza a silhueta e resiste a dias inteiros de evento.",
    especificacoes: [
      "Corpete com armação flexível",
      "Tiara e braceletes em metal leve",
      "Capa em cetim com fecho magnético",
      "Kit com 6 peças",
    ],
    imagens: [
      "https://live.staticflickr.com/8243/8639237614_cc84d1ab96_b.jpg",
      "https://live.staticflickr.com/8383/8639237584_8c09a96f8a_b.jpg",
      "https://live.staticflickr.com/1342/5101201111_e83d6aa1bf_b.jpg",
    ],
  },
  {
    id: 14,
    nome: "Traje Vigilante Noturno — Armadura Tática",
    categoria: "heroes",
    preco: 529.90,
    precoAntigo: null,
    avaliacao: 4.7,
    numAvaliacoes: 82,
    vendas: 104,
    novidade: true,
    destaque: true,
    tamanhos: ["M", "G", "GG"],
    estoque: 9,
    tag: "superhero,mask",
    descricao:
      "Traje tático de vigilante com placas de proteção em EVA flexível, capa semi-rígida, máscara com lentes de espelho e cinto utilitário modular. Mobilidade total para patrulhar a convenção inteira.",
    especificacoes: [
      "Placas EVA flexíveis desmontáveis",
      "Máscara com lentes espelhadas",
      "Cinto utilitário com 4 bolsos",
      "Tecido quatro-way-stretch",
    ],
    imagens: [
      "https://live.staticflickr.com/3020/2290607758_99322fa338_b.jpg",
      "https://live.staticflickr.com/3321/3516008114_bd54764cd1_b.jpg",
      "https://live.staticflickr.com/8519/8638125491_39a52e41d6_b.jpg",
    ],
  },
  {
    id: 15,
    nome: "Varinha Mágica Premium + Suporte de Exibição",
    categoria: "acessorios",
    preco: 189.90,
    precoAntigo: 219.90,
    avaliacao: 4.9,
    numAvaliacoes: 231,
    vendas: 389,
    novidade: false,
    destaque: true,
    tamanhos: ["Único"],
    estoque: 30,
    tag: "magic,wand",
    descricao:
      "Varinha esculpida artesanalmente em madeira com núcleo iluminado por LED ativado por movimento, caixa-presente de luxo e suporte de exibição. Cada peça é única — o acessório que faltava para completar seu uniforme mágico.",
    especificacoes: [
      "Madeira esculpida à mão",
      "LED sensível a movimento",
      "Caixa-presente + suporte inclusos",
      "Pilhas substituíveis",
    ],
    imagens: [
      "https://live.staticflickr.com/8266/29645615526_935b3283dc_b.jpg",
      "https://live.staticflickr.com/8846/29435340796_ed310d9310_b.jpg",
      "https://live.staticflickr.com/8393/29267260801_283ab8f147_b.jpg",
    ],
  },
  {
    id: 16,
    nome: "Katana Decorativa Forjada — Lâmina Ornamental",
    categoria: "acessorios",
    preco: 349.90,
    precoAntigo: 399.90,
    avaliacao: 4.8,
    numAvaliacoes: 127,
    vendas: 198,
    novidade: false,
    destaque: false,
    tamanhos: ["Único"],
    estoque: 18,
    tag: "katana,sword",
    descricao:
      "Katana ornamental com lâmina de aço inox polida espelho, tsuba (guarda) em liga detalhada e bainha lacada. Acompanha suporte de parede em madeira. Produto decorativo — não corta.",
    especificacoes: [
      "Lâmina inox polida espelho",
      "Empunhadura com ray skin sintético",
      "Suporte de parede incluso",
      "Produto decorativo (sem corte)",
    ],
    imagens: [
      "https://live.staticflickr.com/3728/9885787776_555ba68ee2_b.jpg",
      "https://live.staticflickr.com/1538/26501309632_d244dc6678_b.jpg",
      "https://live.staticflickr.com/1749/27665648557_4810f041c1_b.jpg",
    ],
  },
  {
    id: 17,
    nome: "Máscara Kitsune Artesanal — Raposa Espiritual",
    categoria: "acessorios",
    preco: 159.90,
    precoAntigo: null,
    avaliacao: 4.9,
    numAvaliacoes: 176,
    vendas: 302,
    novidade: true,
    destaque: true,
    tamanhos: ["Único"],
    estoque: 25,
    tag: "mask,japan",
    descricao:
      "Máscara de raposa kitsune esculpida e pintada à mão, com elástico ajustável e acabamento em verniz fosco. Leve e confortável — pode ser usada no rosto ou como item de decoração.",
    especificacoes: [
      "Pintura artesanal individual",
      "Fibra de vidro leve (280g)",
      "Elástico ajustável",
      "Verniz fosco protetivo",
    ],
    imagens: [
      "https://live.staticflickr.com/5176/5500387788_24a96c7483_b.jpg",
      "https://live.staticflickr.com/138/340766382_076ae3c062_b.jpg",
      "https://live.staticflickr.com/7334/16405813122_7edbb3d50b_b.jpg",
    ],
  },
  {
    id: 18,
    nome: "Colar do Contrato Sombrio — Amuleto Gótico",
    categoria: "acessorios",
    preco: 89.90,
    precoAntigo: 119.90,
    avaliacao: 4.6,
    numAvaliacoes: 94,
    vendas: 167,
    novidade: false,
    destaque: false,
    tamanhos: ["Único"],
    estoque: 40,
    tag: "necklace,gothic",
    descricao:
      "Amuleto gótico em malha persa completa com banho envelhecido e pingente de pedra vulcânica. Corrente ajustável de 50 a 70cm com fecho reforçado. Um pacto estiloso com o lado sombrio.",
    especificacoes: [
      "Malha chain maille artesanal",
      "Banho envelhecido antialérgico",
      "Pingente de pedra vulcânica",
      "Corrente ajustável 50–70cm",
    ],
    imagens: [
      "https://live.staticflickr.com/3454/3885315586_7fb51dd058_b.jpg",
      "https://live.staticflickr.com/3435/3885315374_d0c53da34b_b.jpg",
      "https://live.staticflickr.com/4144/5162422454_14bf811f80_b.jpg",
    ],
  },

  /* ---------------- Novidades da coleção ---------------- */

  {
    id: 19,
    nome: "Peruca Cosplay Rosa Choque — Fibra Resistente ao Calor",
    categoria: "acessorios",
    preco: 149.90,
    precoAntigo: 179.90,
    avaliacao: 4.7,
    numAvaliacoes: 156,
    vendas: 288,
    novidade: true,
    destaque: true,
    tamanhos: ["Único"],
    estoque: 26,
    tag: "wig,pink",
    descricao:
      "Peruca de fibra sintética premium resiste a temperaturas de até 180°C, permitindo modelar com chapinha ou babyliss. Rede interna ajustável com pinos de segurança e franja pré-estilizada. Pronta para transformar seu cosplay.",
    especificacoes: [
      "Fibra resistente ao calor (até 180°C)",
      "Rede interna ajustável",
      "Franja pré-estilizada",
      "Acompanha peruca-cap para proteger o cabelo",
    ],
    imagens: [
      "https://live.staticflickr.com/6082/6099384805_53b31e5843_b.jpg",
      "https://live.staticflickr.com/6065/6099385157_daf44764be_b.jpg",
      "https://live.staticflickr.com/6207/6099385887_fe91a22ca7_b.jpg",
    ],
  },
  {
    id: 20,
    nome: "Peruca Cosplay Azul Oceano — Corte Longo Lisa",
    categoria: "acessorios",
    preco: 159.90,
    precoAntigo: null,
    avaliacao: 4.8,
    numAvaliacoes: 121,
    vendas: 203,
    novidade: true,
    destaque: false,
    tamanhos: ["Único"],
    estoque: 19,
    tag: "wig,blue",
    descricao:
      "Fios longos e sedosos em azul profundo com brilho acetinado. Estrutura ventilada que reduz o suor durante eventos longos e mechas naturais sem embolar. Ideal para personagens de anime e fantasy.",
    especificacoes: [
      "Comprimento 80cm",
      "Estrutura ventilada",
      "Cor sólida sem desbotar",
      "Escova de manutenção inclusa",
    ],
    imagens: [
      "https://live.staticflickr.com/778/23027656091_d2d40b982a_b.jpg",
      "https://live.staticflickr.com/1681/25844635743_19a92b2414_b.jpg",
      "https://live.staticflickr.com/1480/25847220074_317820e532_b.jpg",
    ],
  },
  {
    id: 21,
    nome: "Peruca Loira Dourada — Edição Herói Link",
    categoria: "acessorios",
    preco: 139.90,
    precoAntigo: 169.90,
    avaliacao: 4.6,
    numAvaliacoes: 98,
    vendas: 176,
    novidade: true,
    destaque: false,
    tamanhos: ["Único"],
    estoque: 21,
    tag: "wig,blonde",
    descricao:
      "Loira dourada vibrante inspirada nos heróis de videogame, com fios resistentes e boné interno confortável. Combina com personagens de RPG, aventura e fantasia medieval.",
    especificacoes: [
      "Fibra sintética macia",
      "Boné interno com regulagem",
      "Formato versátil para penteados",
      "Embalagem protetora reutilizável",
    ],
    imagens: [
      "https://live.staticflickr.com/65535/49061940808_2a12095f6e.jpg",
      "https://live.staticflickr.com/2917/14736485551_f19e215ced_b.jpg",
      "https://live.staticflickr.com/6083/6099933066_c95d371241_b.jpg",
    ],
  },
  {
    id: 22,
    nome: "Chapéu de Bruxa Clássico — Veludo com Fivela",
    categoria: "medieval",
    preco: 99.90,
    precoAntigo: 129.90,
    avaliacao: 4.5,
    numAvaliacoes: 87,
    vendas: 165,
    novidade: true,
    destaque: false,
    tamanhos: ["Único"],
    estoque: 32,
    tag: "witch,hat",
    descricao:
      "Chapéu de ponta curva em veludo premium com aba estruturada que não amassa na mochila. Fivela metálica envelhecida e faixa contrastante. Clássico das bruxas, perfeito para Halloween e composições mágicas.",
    especificacoes: [
      "Veludo premium antirrugas",
      "Aba estruturada 45cm",
      "Fivela metálica envelhecida",
      "Tamanho ajustável interno",
    ],
    imagens: [
      "https://live.staticflickr.com/2398/1849512851_1435bbecea_b.jpg",
      "https://live.staticflickr.com/49/173826937_846f125b4b_b.jpg",
      "https://live.staticflickr.com/2358/4507045346_9024220af2_b.jpg",
    ],
  },
  {
    id: 23,
    nome: "Espada Longa Medieval — Réplica Decorativa Albion",
    categoria: "medieval",
    preco: 899.90,
    precoAntigo: 1049.90,
    avaliacao: 4.9,
    numAvaliacoes: 54,
    vendas: 67,
    novidade: true,
    destaque: true,
    tamanhos: ["Único"],
    estoque: 5,
    tag: "sword,medieval",
    descricao:
      "Réplica decorativa de espada longa com lâmina de aço inox fosco, empunhadura encordoada e pomo em liga maciça. Balanceamento visual fiel aos originais do século XV. Acompanha bainha de couro sintético.",
    especificacoes: [
      "Lâmina 90cm em aço inox fosco",
      "Empunhadura encordoada",
      "Pomo e guarda em liga maciça",
      "Bainha em couro sintético inclusa",
    ],
    imagens: [
      "https://live.staticflickr.com/2926/14411871202_3fc7500a66_b.jpg",
      "https://live.staticflickr.com/2893/12185322773_3fceefc5c3_b.jpg",
      "https://live.staticflickr.com/8219/29325800180_025670766d_b.jpg",
    ],
  },
  {
    id: 24,
    nome: "Escudo Heráldico de Cavaleiro — Aço e Brasão",
    categoria: "medieval",
    preco: 549.90,
    precoAntigo: null,
    avaliacao: 4.7,
    numAvaliacoes: 41,
    vendas: 52,
    novidade: true,
    destaque: false,
    tamanhos: ["Único"],
    estoque: 8,
    tag: "shield,heraldry",
    descricao:
      "Escudo heráldico em madeira compensada com chapa de aço frontal, brasão pintado à mão e alças de braço acolchoadas. Suporte de parede incluso para exibir entre eventos.",
    especificacoes: [
      "Madeira compensada 18mm",
      "Chapa de aço frontal",
      "Brasão pintado à mão",
      "Alças acolchoadas + suporte de parede",
    ],
    imagens: [
      "https://live.staticflickr.com/65535/49350370803_2402546290_b.jpg",
      "https://live.staticflickr.com/7231/7225524432_9857caa537_b.jpg",
    ],
  },
  {
    id: 25,
    nome: "Coroa Real Réplica — Metal Envelhecido",
    categoria: "acessorios",
    preco: 279.90,
    precoAntigo: 319.90,
    avaliacao: 4.8,
    numAvaliacoes: 63,
    vendas: 84,
    novidade: true,
    destaque: false,
    tamanhos: ["Único"],
    estoque: 12,
    tag: "crown,gold",
    descricao:
      "Coroa réplica em metal leve com banho dourado envelhecido e detalhes repuxados à mão. Interior acolchoado em veludo para conforto durante cerimônias temáticas, casamentos nerd e ensaios fotográficos.",
    especificacoes: [
      "Metal leve com banho dourado",
      "Detalhes repuxados à mão",
      "Interior em veludo acolchoado",
      "Caixa rígida para transporte",
    ],
    imagens: [
      "https://upload.wikimedia.org/wikipedia/commons/0/0f/Medieval_Crown_of_Bulgaria.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/d/d3/Post-medieval_crown_mount_%28FindID_224923%29.jpg",
    ],
  },
  {
    id: 26,
    nome: "Figure Colecionável Chibi Detetive — Nendoroid Style",
    categoria: "anime",
    preco: 249.90,
    precoAntigo: null,
    avaliacao: 4.9,
    numAvaliacoes: 148,
    vendas: 231,
    novidade: true,
    destaque: true,
    tamanhos: ["Único"],
    estoque: 14,
    tag: "figure,chibi",
    descricao:
      "Figure colecionável estilo chibi com rosto intercambiável, três expressões e acessórios temáticos. Base articulada para poses divertidas e caixa com janela de exposição. Item oficial de vitrine para fãs.",
    especificacoes: [
      "PVC pintado à mão",
      "3 rostos intercambiáveis",
      "Base articulada inclusa",
      "Altura aproximada 10cm",
    ],
    imagens: [
      "https://live.staticflickr.com/3354/3343839763_c5149932d2_b.jpg",
      "https://live.staticflickr.com/4129/5091539666_3d20d2bc72_b.jpg",
    ],
  },
  {
    id: 27,
    nome: "Kit 3 Mini-Figuras Mecha — Coleção Clássica",
    categoria: "anime",
    preco: 389.90,
    precoAntigo: 449.90,
    avaliacao: 4.7,
    numAvaliacoes: 77,
    vendas: 112,
    novidade: true,
    destaque: false,
    tamanhos: ["Único"],
    estoque: 9,
    tag: "figure,mecha",
    descricao:
      "Trilogia de mini-figuras dos mechas mais icônicos dos anos 90, com articulações pontuais, pedestais individuais e cartão de colecionador numerado. Presente certo para quem cresceu assistindo.",
    especificacoes: [
      "3 figuras com articulações",
      "Pedestais individuais",
      "Cartão de colecionador numerado",
      "Altura média 12cm cada",
    ],
    imagens: [
      "https://live.staticflickr.com/3288/2669714142_1f731023b0.jpg",
      "https://live.staticflickr.com/3279/2668893365_d761416c74.jpg",
      "https://live.staticflickr.com/3224/2669713992_47083d1e26.jpg",
    ],
  },
  {
    id: 28,
    nome: "Kimono Tradicional Sakura — Algodão Floral",
    categoria: "anime",
    preco: 269.90,
    precoAntigo: null,
    avaliacao: 4.8,
    numAvaliacoes: 92,
    vendas: 141,
    novidade: true,
    destaque: false,
    tamanhos: ["P", "M", "G", "GG"],
    estoque: 17,
    tag: "kimono,floral",
    descricao:
      "Kimono tradicional em algodão leve com estampa floral sakura, mangas amplas e obi contrastante. Confortável para dias inteiros de evento, festival japonês ou um chá da tarde temático.",
    especificacoes: [
      "Algodão 100% respirável",
      "Estampa floral exclusiva",
      "Obi reversível incluso",
      "Corte unissex",
    ],
    imagens: [
      "https://live.staticflickr.com/3922/14787145030_01a635d80b_b.jpg",
      "https://live.staticflickr.com/5245/5337800379_4958bc0b14_b.jpg",
      "https://live.staticflickr.com/5165/5338411488_b85be956a7_b.jpg",
    ],
  },
  {
    id: 29,
    nome: "Manto Peregrino com Capuz — Cinza Viajante",
    categoria: "medieval",
    preco: 319.90,
    precoAntigo: 369.90,
    avaliacao: 4.6,
    numAvaliacoes: 58,
    vendas: 73,
    novidade: true,
    destaque: false,
    tamanhos: ["M", "G", "GG"],
    estoque: 13,
    tag: "cloak,grey",
    descricao:
      "Manto de viagem com capuz profundo em lã fria resistente, ideal para monges, peregrinos e magos errantes. Fecho por broche metálico e bolsos internos discretos para celular e carteira.",
    especificacoes: [
      "Lã fria resistente ao vento",
      "Broche metálico antique",
      "Capuz profundo estruturado",
      "2 bolsos internos",
    ],
    imagens: [
      "https://live.staticflickr.com/223/524522552_e3d57b9a7b_b.jpg",
      "https://live.staticflickr.com/7436/16437275772_1e36445d42_b.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/1/1f/Bardon_Mill%2C_Housesteads_Roman_Fort_Museum%2C_Three_spirits_wearing_hooded_cloaks_-_geograph.org.uk_-_7851709.jpg",
    ],
  },
  {
    id: 30,
    nome: "Elmo Clone Trooper Phase II — Edição Colecionador",
    categoria: "filmes",
    preco: 599.90,
    precoAntigo: 679.90,
    avaliacao: 4.7,
    numAvaliacoes: 69,
    vendas: 91,
    novidade: true,
    destaque: false,
    tamanhos: ["Único"],
    estoque: 7,
    tag: "helmet,trooper",
    descricao:
      "Elmo de clone trooper Phase II com visor azul tintado, pintura em duas camadas e sistema de ajuste interno. Versão colecionador acompanha placa numerada e suporte de mesa em acrílico.",
    especificacoes: [
      "Visor azul tintado UV",
      "Pintura dupla camada",
      "Placa numerada de colecionador",
      "Suporte de mesa em acrílico",
    ],
    imagens: [
      "https://live.staticflickr.com/4876/46313769042_4e7ea9d774_b.jpg",
      "https://live.staticflickr.com/2709/4016842259_fc05b6d2be_b.jpg",
      "https://live.staticflickr.com/4365/36030591774_7c54d43fcc_b.jpg",
    ],
  },
  {
    id: 31,
    nome: "Dupla de Capas Heroínas — Edição Casal",
    categoria: "heroes",
    preco: 359.90,
    precoAntigo: 419.90,
    avaliacao: 4.8,
    numAvaliacoes: 47,
    vendas: 58,
    novidade: true,
    destaque: false,
    tamanhos: ["P", "M", "G"],
    estoque: 11,
    tag: "cape,superhero",
    descricao:
      "Duas capas em cetim pesado (azul e vermelha) com fecho magnético disfarçado, ideais para duplas e casais que posam juntos. Leves, esvoaçantes e fotografam incrivelmente bem em movimento.",
    especificacoes: [
      "2 capas em cetim pesado",
      "Fecho magnético invisível",
      "Barra com costura reforçada",
      "Azul royal + vermelho clássico",
    ],
    imagens: [
      "https://live.staticflickr.com/4056/4571419067_d41615deb2_b.jpg",
    ],
  },
];

function buscarProduto(id) {
  return PRODUTOS.find((p) => p.id === Number(id)) || null;
}

function nomeCategoria(id) {
  const cat = CATEGORIAS.find((c) => c.id === id);
  return cat ? cat.nome : "Outros";
}

function galeriaProduto(p) {
  if (p.imagens && p.imagens.length > 0) return p.imagens.slice(0, 3);
  return [0, 1, 2].map(
    (i) => `https://loremflickr.com/800/1000/${p.tag}?lock=${p.id * 10 + i}`
  );
}

function imagemPrincipal(p) {
  return galeriaProduto(p)[0];
}

function imagemThumbnail(p) {
  const url = imagemPrincipal(p);
  if (url.includes("live.staticflickr.com")) return url.replace("_b.jpg", "_z.jpg");
  return url;
}

function fallbackImagem(seed) {
  return `https://picsum.photos/seed/cosplayhub-${seed}/800/1000`;
}
