/* ============================================================
   CosplayHub — Catálogo de dados (produtos e categorias)
   Imagens: LoremFlickr (banco gratuito) com fallback Picsum
   ============================================================ */

const CATEGORIAS = [
  { id: "anime",     nome: "Anime & Mangá",        icone: "bi-tv",          tag: "cosplay,anime" },
  { id: "filmes",    nome: "Filmes & Séries",      icone: "bi-film",        tag: "movie,costume" },
  { id: "games",     nome: "Games",                icone: "bi-controller",  tag: "gaming,costume" },
  { id: "heroes",    nome: "Super-Herois",         icone: "bi-lightning-charge-fill", tag: "superhero" },
  { id: "medieval",  nome: "Fantasia & Medieval",  icone: "bi-shield-shaded", tag: "medieval,knight" },
  { id: "acessorios", nome: "Acessórios & Props",  icone: "bi-gem",         tag: "mask,prop" },
];

const PRODUTOS = [
  {
    id: 1,
    nome: "Kimono Xadrez Tanjiro — Réplica Premium",
    categoria: "anime",
    preco: 289.90,
    precoAntigo: 349.90,
    avaliacao: 4.9,
    numAvaliacoes: 214,
    vendas: 512,
    novidade: false,
    destaque: true,
    tamanhos: ["P", "M", "G", "GG"],
    estoque: 14,
    tag: "kimono,japan",
    descricao:
      "Réplica fiel do kimono xadrez usado por Tanjiro Kamado. Tecido em sarja leve com estampa em alta definição, costuras reforçadas e caimento confortável para uso prolongado em convenções e eventos. Acompanha faixa obi decorativa.",
    especificacoes: [
      "Tecido: sarja de poliéster premium",
      "Estampa sublimada em alta definição",
      "Acompanha faixa obi",
      "Lavagem à máquina (ciclo delicado)",
    ],
  },
  {
    id: 2,
    nome: "Manto Akatsuki — Nuvens Vermelhas Bordado",
    categoria: "anime",
    preco: 259.90,
    precoAntigo: 299.90,
    avaliacao: 4.8,
    numAvaliacoes: 187,
    vendas: 430,
    novidade: false,
    destaque: true,
    tamanhos: ["P", "M", "G", "GG"],
    estoque: 22,
    tag: "cosplay,red",
    descricao:
      "O manto icônico da Akatsuki com nuvens vermelhas bordadas em alto relevo. Interior forrado, gola alta estruturada e tecido resistente ao vento — perfeito para composições de personagem ou uso casual geek.",
    especificacoes: [
      "Nuvens bordadas (não estampadas)",
      "Forro interno em cetim",
      "Gola alta estruturada",
      "Bolsos internos discretos",
    ],
  },
  {
    id: 3,
    nome: "Uniforme de Feiticeiro Jujutsu — Edição Batalha",
    categoria: "anime",
    preco: 319.90,
    precoAntigo: null,
    avaliacao: 4.7,
    numAvaliacoes: 143,
    vendas: 265,
    novidade: true,
    destaque: true,
    tamanhos: ["P", "M", "G", "GG"],
    estoque: 9,
    tag: "cosplay,japan",
    descricao:
      "Uniforme escolar de feiticeiro com acabamento premium: gola alta assimétrica, botões metálicos gravados e tecido com leve elasticidade para liberdade de movimento durante performances e competições de cosplay.",
    especificacoes: [
      "Tecido com elastano (stretch)",
      "Botões metálicos gravados",
      "Costura dupla nos pontos de tensão",
      "Kit com 3 peças: casaco, calça e faixa",
    ],
  },
  {
    id: 4,
    nome: "Armadura de Samurai Completa — Aço Escovado",
    categoria: "medieval",
    preco: 1299.90,
    precoAntigo: 1499.90,
    avaliacao: 5.0,
    numAvaliacoes: 76,
    vendas: 98,
    novidade: false,
    destaque: true,
    tamanhos: ["Único"],
    estoque: 4,
    tag: "samurai,armor",
    descricao:
      "Armadura de samurai em EVA de alta densidade com pintura efeito aço escovado. Conjunto completo com dou (peitoral), kabuto (elmo), ombreiras, manicas e hakama. Montagem intuitiva com tiras de velcro ocultas.",
    especificacoes: [
      "EVA 10mm de alta densidade",
      "Pintura com efeito metálico",
      "Conjunto com 7 peças",
      "Ajuste por velcro e elásticos internos",
    ],
  },
  {
    id: 5,
    nome: "Armadura de Cavaleiro Medieval — Guardião Real",
    categoria: "medieval",
    preco: 1199.90,
    precoAntigo: null,
    avaliacao: 4.8,
    numAvaliacoes: 64,
    vendas: 87,
    novidade: true,
    destaque: true,
    tamanhos: ["Único"],
    estoque: 6,
    tag: "knight,armor",
    descricao:
      "Armadura completa de cavaleiro com peitoral articulado, escarcela e elmo com viseira móvel. Ideais para LARP, feiras medievais e fotografia temática. Acabamento envelhecido artesanal peça a peça.",
    especificacoes: [
      "Viseira móvel funcional",
      "Peitoral articulado",
      "Acabamento envelhecido manual",
      "Suporte de exibição incluído",
    ],
  },
  {
    id: 6,
    nome: "Trajo Viking Ragnar — Pele e Malha de Combate",
    categoria: "medieval",
    preco: 899.90,
    precoAntigo: 999.90,
    avaliacao: 4.7,
    numAvaliacoes: 58,
    vendas: 74,
    novidade: false,
    destaque: true,
    tamanhos: ["M", "G", "GG"],
    estoque: 8,
    tag: "viking,warrior",
    descricao:
      "Trajo viking inspirado em séries épicas: túnica de malha metálica simulada, sobretudo de pele sintética, cinto de couro legítimo com fivela rúnica e perneiras. Um visual imponente e pronto para a batalha.",
    especificacoes: [
      "Couro legítimo no cinto",
      "Pele sintética premium",
      "Malha simulada leve (não é metal)",
      "4 peças + acessórios",
    ],
  },
  {
    id: 7,
    nome: "Capacete Stormtrooper — Réplica Colecionável",
    categoria: "filmes",
    preco: 649.90,
    precoAntigo: null,
    avaliacao: 4.6,
    numAvaliacoes: 112,
    vendas: 156,
    novidade: false,
    destaque: true,
    tamanhos: ["Único"],
    estoque: 11,
    tag: "helmet,starwars",
    descricao:
      "Réplica colecionável do capacete de Stormtrooper com lentes espelhadas e sistema interno de ajuste. Vem com base de exposição acrílica e certificado de edição limitada.",
    especificacoes: [
      "ABS injeção com pintura UV",
      "Lentes espelhadas removíveis",
      "Acolchoamento interno ajustável",
      "Base acrílica inclusa",
    ],
  },
  {
    id: 8,
    nome: "Manto de Jedi + Sabre de Luz Retrátil",
    categoria: "filmes",
    preco: 749.90,
    precoAntigo: 849.90,
    avaliacao: 4.8,
    numAvaliacoes: 95,
    vendas: 132,
    novidade: false,
    destaque: true,
    tamanhos: ["P", "M", "G", "GG"],
    estoque: 13,
    tag: "starwars,costume",
    descricao:
      "Kit completo de Jedi: manto externo com capuz profundo, túnica interna, faixa cinturão e sabre de luz retrátil com iluminação LED e efeitos sonoros de batalha. Que a Força esteja com você.",
    especificacoes: [
      "Sabre LED com som (pilhas inclusas)",
      "Lâmina retrátil de 90cm",
      "Manto em crepe pesado",
      "Kit com 5 peças",
    ],
  },
  {
    id: 9,
    nome: "Capuz e Manto Sith — Edição Sombria",
    categoria: "filmes",
    preco: 599.90,
    precoAntigo: null,
    avaliacao: 4.5,
    numAvaliacoes: 71,
    vendas: 89,
    novidade: true,
    destaque: false,
    tamanhos: ["P", "M", "G", "GG"],
    estoque: 16,
    tag: "halloween,hood",
    descricao:
      "Conjunto de manto longo com capuz estruturado e túnica interna em tons profundos de preto e cinza. Silhueta dramática garantida — do lado sombrio direto para o palco do concurso de cosplay.",
    especificacoes: [
      "Capuz com armação interna removível",
      "Tecido fluído anti-amassado",
      "Comprimento total 145cm",
      "2 peças",
    ],
  },
  {
    id: 10,
    nome: "Jaqueta Cyberpunk Neon — Circuito Luminoso",
    categoria: "games",
    preco: 479.90,
    precoAntigo: 559.90,
    avaliacao: 4.9,
    numAvaliacoes: 168,
    vendas: 241,
    novidade: true,
    destaque: true,
    tamanhos: ["P", "M", "G", "GG"],
    estoque: 10,
    tag: "cyberpunk,neon",
    descricao:
      "Jaqueta futurista com trilhas de LED costuradas e controlador USB recarregável com 7 modos de luz. Tecido refletivo reage ao flash das câmeras — feita para arrancar suspiros na pista e nas fotos.",
    especificacoes: [
      "LEDs com 7 modos + controle USB",
      "Bateria recarregável (6h de autonomia)",
      "Tecido refletivo premium",
      "Lavável removendo o módulo eletrônico",
    ],
  },
  {
    id: 11,
    nome: "Jaqueta Couro Vault Survivor — Pós-Apocalíptica",
    categoria: "games",
    preco: 399.90,
    precoAntigo: null,
    avaliacao: 4.6,
    numAvaliacoes: 87,
    vendas: 118,
    novidade: false,
    destaque: false,
    tamanhos: ["P", "M", "G", "GG"],
    estoque: 12,
    tag: "leather,jacket",
    descricao:
      "Jaqueta de couro sintético com patches bordados do Refúgio, zíperes metálicos YKK e forro térmico. Resistente, estilosa e pronta para sobreviver a qualquer wasteland — inclusive à fila da convenção.",
    especificacoes: [
      "Couro sintético PU premium",
      "Zíperes metálicos YKK",
      "Forro térmico removível",
      "Patches bordados exclusivos",
    ],
  },
  {
    id: 12,
    nome: "Elmo do Cavaleiro do Abismo — RPG Sombrio",
    categoria: "games",
    preco: 549.90,
    precoAntigo: null,
    avaliacao: 4.7,
    numAvaliacoes: 49,
    vendas: 63,
    novidade: false,
    destaque: true,
    tamanhos: ["Único"],
    estoque: 7,
    tag: "helmet,armor",
    descricao:
      "Elmo inspirado nos cavaleiros sombrios dos RPGs de ação, com chifres esculpidos, viseira gradeada e interior acolchoado. Peça de destaque absoluto em qualquer composição dark fantasy.",
    especificacoes: [
      "Chifres em resina resistente",
      "Interior acolchoado removível",
      "Viseira gradeada ventilada",
      "Acabamento matte envelhecido",
    ],
  },
  {
    id: 13,
    nome: "Capa Wonder Warrior — Coroa e Braceletes",
    categoria: "heroes",
    preco: 449.90,
    precoAntigo: 519.90,
    avaliacao: 4.8,
    numAvaliacoes: 103,
    vendas: 147,
    novidade: false,
    destaque: true,
    tamanhos: ["P", "M", "G"],
    estoque: 15,
    tag: "superhero,red",
    descricao:
      "Conjunto de guerreira amazona com corpete estruturado, capa em cetim, tiara metálica e braceletes de combate. Modelagem anatômica que valoriza a silhueta e resiste a dias inteiros de evento.",
    especificacoes: [
      "Corpete com armação flexível",
      "Tiara e braceletes em metal leve",
      "Capa em cetim com fecho magnético",
      "Kit com 6 peças",
    ],
  },
  {
    id: 14,
    nome: "Traje Vigilante Noturno — Armadura Tática",
    categoria: "heroes",
    preco: 529.90,
    precoAntigo: null,
    avaliacao: 4.7,
    numAvaliacoes: 82,
    vendas: 104,
    novidade: true,
    destaque: true,
    tamanhos: ["M", "G", "GG"],
    estoque: 9,
    tag: "superhero,mask",
    descricao:
      "Traje tático de vigilante com placas de proteção em EVA flexível, capa semi-rígida, máscara com lentes de espelho e cinto utilitário modular. Mobilidade total para patrulhar a convenção inteira.",
    especificacoes: [
      "Placas EVA flexíveis desmontáveis",
      "Máscara com lentes espelhadas",
      "Cinto utilitário com 4 bolsos",
      "Tecido quatro-way-stretch",
    ],
  },
  {
    id: 15,
    nome: "Varinha Mágica Premium + Suporte de Exibição",
    categoria: "acessorios",
    preco: 189.90,
    precoAntigo: 219.90,
    avaliacao: 4.9,
    numAvaliacoes: 231,
    vendas: 389,
    novidade: false,
    destaque: true,
    tamanhos: ["Único"],
    estoque: 30,
    tag: "magic,wand",
    descricao:
      "Varinha esculpida em resina com núcleo iluminado por LED ativado por movimento, caixa-presente de luxo e suporte de exibição. O acessório que faltava para completar seu uniforme mágico.",
    especificacoes: [
      "LED sensível a movimento",
      "Resina com detalhes esculpidos à mão",
      "Caixa-presente + suporte inclusos",
      "Pilhas substituíveis",
    ],
  },
  {
    id: 16,
    nome: "Katana Decorativa Forjada — Lâmina Ornamental",
    categoria: "acessorios",
    preco: 349.90,
    precoAntigo: 399.90,
    avaliacao: 4.8,
    numAvaliacoes: 127,
    vendas: 198,
    novidade: false,
    destaque: false,
    tamanhos: ["Único"],
    estoque: 18,
    tag: "katana,sword",
    descricao:
      "Katana ornamental com lâmina de aço inox polida espelho, tsuba (guarda) em liga detalhada e bainha lacada. Acompanha suporte de parede em madeira. Produto decorativo — não corta.",
    especificacoes: [
      "Lâmina inox polida espelho",
      "Empunhadura com ray skin sintético",
      "Suporte de parede incluso",
      "Produto decorativo (sem corte)",
    ],
  },
  {
    id: 17,
    nome: "Máscara Kitsune Artesanal — Raposa Espiritual",
    categoria: "acessorios",
    preco: 159.90,
    precoAntigo: null,
    avaliacao: 4.9,
    numAvaliacoes: 176,
    vendas: 302,
    novidade: true,
    destaque: true,
    tamanhos: ["Único"],
    estoque: 25,
    tag: "mask,japan",
    descricao:
      "Máscara de raposa kitsune esculpida e pintada à mão, com elástico ajustável e acabamento em verniz fosco. Leve e confortável — pode ser usada no rosto ou como item de decoração.",
    especificacoes: [
      "Pintura artesanal individual",
      "Fibra de vidro leve (280g)",
      "Elástico ajustável",
      "Verniz fosco protetivo",
    ],
  },
  {
    id: 18,
    nome: "Colar do Contrato Sombrio — Amuleto Gótico",
    categoria: "acessorios",
    preco: 89.90,
    precoAntigo: 119.90,
    avaliacao: 4.6,
    numAvaliacoes: 94,
    vendas: 167,
    novidade: false,
    destaque: false,
    tamanhos: ["Único"],
    estoque: 40,
    tag: "necklace,gothic",
    descricao:
      "Amuleto gótico em liga de zinco com banho envelhecido e pedra obsidiana central. Corrente ajustável de 50 a 70cm com fecho reforçado. Um pacto estiloso com o lado sombrio.",
    especificacoes: [
      "Banho envelhecido antialérgico",
      "Pedra natural obsidiana",
      "Corrente ajustável 50–70cm",
      "Acompanha saqueto de veludo",
    ],
  },
];

function buscarProduto(id) {
  return PRODUTOS.find((p) => p.id === Number(id)) || null;
}

function nomeCategoria(id) {
  const cat = CATEGORIAS.find((c) => c.id === id);
  return cat ? cat.nome : "Outros";
}

function imagemProduto(produto, indice = 0, largura = 800, altura = 1000) {
  const lock = produto.id * 10 + indice;
  return `https://loremflickr.com/${largura}/${altura}/${produto.tag}?lock=${lock}`;
}

function fallbackImagem(seed, largura = 800, altura = 1000) {
  return `https://picsum.photos/seed/cosplayhub-${seed}/${largura}/${altura}`;
}
